/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
// =============================================================================
// FILENAME: PSoCAPI.h
// 
// Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
// 
// NOTES:
// Do not modify this file. It is generated by PSoC Designer each time the
// generate application function is run. The values of the parameters in this
// file can be modified by changing the values of the global parameters in the
// device editor.
// 
// =============================================================================
 
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "Counter16_PwrUpd.h"
#include "Counter8_RF_clk.h"
#include "LCD.h"
#include "LED_Blue.h"
#include "PWM16_CH0.h"
#include "PWM16_CH1.h"
#include "RTC.h"
#include "RX8_GPS.h"
#include "RX8_RF.h"
#include "TX8_Debug.h"

#endif
