/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// LED_BluePin address and mask defines
#pragma	ioport	LED_BluePin_Data_ADDR:	0x4
BYTE			LED_BluePin_Data_ADDR;
#pragma	ioport	LED_BluePin_DriveMode_0_ADDR:	0x104
BYTE			LED_BluePin_DriveMode_0_ADDR;
#pragma	ioport	LED_BluePin_DriveMode_1_ADDR:	0x105
BYTE			LED_BluePin_DriveMode_1_ADDR;
#pragma	ioport	LED_BluePin_DriveMode_2_ADDR:	0x7
BYTE			LED_BluePin_DriveMode_2_ADDR;
#pragma	ioport	LED_BluePin_GlobalSelect_ADDR:	0x6
BYTE			LED_BluePin_GlobalSelect_ADDR;
#pragma	ioport	LED_BluePin_IntCtrl_0_ADDR:	0x106
BYTE			LED_BluePin_IntCtrl_0_ADDR;
#pragma	ioport	LED_BluePin_IntCtrl_1_ADDR:	0x107
BYTE			LED_BluePin_IntCtrl_1_ADDR;
#pragma	ioport	LED_BluePin_IntEn_ADDR:	0x5
BYTE			LED_BluePin_IntEn_ADDR;
#define LED_BluePin_MASK 0x10
#pragma	ioport	LED_BluePin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_BluePin_MUXBusCtrl_ADDR;
// LED_BluePin Shadow defines
//   LED_BluePin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_BluePin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
