Project:      output/FitoLamp_slave
Build Number: 0
Date:         Wed Nov 09 10:50:43 2022
Compiler:     ICCM8C
Version:      7.05.00


Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                             lit   0190   02A6 =    678. bytes (rel,con,rom,lit)

       Addr  Global Symbol
      -----  --------------------------------
       0190  _hw_id
       0192  _cmd_on
       0195  _cmd_off
       0199  _cmd_fon
       019D  _cmd_foff
       01A2  _schedule
       01B7  LoadConfigTBL_fitolamp_slave_Bank0
       0256  LoadConfigTBL_fitolamp_slave_Bank1
       0335  __ctype
       0436  __lit_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                        func_lit   0436   0002 =      2. bytes (rel,con,rom,proclab)

       Addr  Global Symbol
      -----  --------------------------------
       0436  __func_lit_start
       0438  __func_lit_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                     psoc_config   0438   012A =    298. bytes (rel,con,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       0438  LoadConfigTBL_fitolamp_slave_Ordered
       04FD  _LoadConfigInit
       04FD  LoadConfigInit
       0507  _LoadConfig_fitolamp_slave
       0507  LoadConfig_fitolamp_slave
       0562  __psoc_config_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                     UserModules   0562   0771 =   1905. bytes (rel,con,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       0562  _TX8_Debug_ISR
       0563  _TX8_Debug_EnableInt
       0563  TX8_Debug_EnableInt
       0567  _TX8_Debug_DisableInt
       0567  TX8_Debug_DisableInt
       056B  TX8_Debug_SetTxIntMode
       056B  _TX8_Debug_SetTxIntMode
       057D  TX8_Debug_Start
       057D  _TX8_Debug_Start
       0582  _TX8_Debug_Stop
       0582  TX8_Debug_Stop
       0586  TX8_Debug_SendData
       0586  _TX8_Debug_SendData
       0589  _TX8_Debug_bReadTxStatus
       0589  TX8_Debug_bReadTxStatus
       0589  bTX8_Debug_ReadTxStatus
       0589  _bTX8_Debug_ReadTxStatus
       059C  _TX8_Debug_PutSHexByte
       059C  TX8_Debug_PutSHexByte
       05AF  _TX8_Debug_PutSHexInt
       05AF  TX8_Debug_PutSHexInt
       05B6  TX8_Debug_PutChar
       05B6  _TX8_Debug_PutChar
       05BE  _TX8_Debug_PutString
       05BE  TX8_Debug_PutString
       05D0  _TX8_Debug_Write
       05D0  TX8_Debug_Write
       05F8  _TX8_Debug_CWrite
       05F8  TX8_Debug_CWrite
       0620  _TX8_Debug_CPutString
       0620  TX8_Debug_CPutString
       0632  _TX8_Debug_PutCRLF
       0632  TX8_Debug_PutCRLF
       063B  _RX8_RF_ISR
       073D  _RX8_RF_EnableInt
       073D  RX8_RF_EnableInt
       0741  _RX8_RF_DisableInt
       0741  RX8_RF_DisableInt
       0745  _RX8_RF_Start
       0745  RX8_RF_Start
       074A  _RX8_RF_Stop
       074A  RX8_RF_Stop
       074E  _RX8_RF_bReadRxData
       074E  _bRX8_RF_ReadRxData
       074E  RX8_RF_bReadRxData
       074E  bRX8_RF_ReadRxData
       0751  _bRX8_RF_ReadRxStatus
       0751  _RX8_RF_bReadRxStatus
       0751  bRX8_RF_ReadRxStatus
       0751  RX8_RF_bReadRxStatus
       0754  RX8_RF_cGetChar
       0754  _RX8_RF_cGetChar
       075C  RX8_RF_cReadChar
       075C  _RX8_RF_cReadChar
       0773  RX8_RF_iReadChar
       0773  _RX8_RF_iReadChar
       0789  _RX8_RF_CmdReset
       0789  RX8_RF_CmdReset
       079F  _RX8_RF_bCmdCheck
       079F  RX8_RF_bCmdCheck
       07A7  _RX8_RF_bErrCheck
       07A7  RX8_RF_bErrCheck
       07B2  _RX8_RF_bCmdLength
       07B2  RX8_RF_bCmdLength
       07B8  _RX8_RF_szGetParam
       07B8  RX8_RF_szGetParam
       0816  RX8_RF_szGetRestOfParams
       0816  _RX8_RF_szGetRestOfParams
       0821  _RX8_GPS_ISR
       0923  RX8_GPS_EnableInt
       0923  _RX8_GPS_EnableInt
       0927  _RX8_GPS_DisableInt
       0927  RX8_GPS_DisableInt
       092B  _RX8_GPS_Start
       092B  RX8_GPS_Start
       0930  RX8_GPS_Stop
       0930  _RX8_GPS_Stop
       0934  RX8_GPS_bReadRxData
       0934  bRX8_GPS_ReadRxData
       0934  _bRX8_GPS_ReadRxData
       0934  _RX8_GPS_bReadRxData
       0937  bRX8_GPS_ReadRxStatus
       0937  _RX8_GPS_bReadRxStatus
       0937  _bRX8_GPS_ReadRxStatus
       0937  RX8_GPS_bReadRxStatus
       093A  RX8_GPS_cGetChar
       093A  _RX8_GPS_cGetChar
       0942  _RX8_GPS_cReadChar
       0942  RX8_GPS_cReadChar
       0959  RX8_GPS_iReadChar
       0959  _RX8_GPS_iReadChar
       096F  _RX8_GPS_CmdReset
       096F  RX8_GPS_CmdReset
       0985  RX8_GPS_bCmdCheck
       0985  _RX8_GPS_bCmdCheck
       098D  RX8_GPS_bErrCheck
       098D  _RX8_GPS_bErrCheck
       0998  RX8_GPS_bCmdLength
       0998  _RX8_GPS_bCmdLength
       099E  RX8_GPS_szGetParam
       099E  _RX8_GPS_szGetParam
       09FC  RX8_GPS_szGetRestOfParams
       09FC  _RX8_GPS_szGetRestOfParams
       0A07  _RTC_ISR
       0A08  RTC_EnableInt
       0A08  _RTC_EnableInt
       0A13  RTC_DisableInt
       0A13  _RTC_DisableInt
       0A1E  _RTC_ClearInt
       0A1E  RTC_ClearInt
       0A22  RTC_Start
       0A22  _RTC_Start
       0A2A  RTC_Stop
       0A2A  _RTC_Stop
       0A32  RTC_SetIntPeriod
       0A32  _RTC_SetIntPeriod
       0A48  RTC_bReadSecond
       0A48  _RTC_bReadSecond
       0A4F  RTC_bReadMinute
       0A4F  _RTC_bReadMinute
       0A56  RTC_bReadHour
       0A56  _RTC_bReadHour
       0A5D  RTC_SetSecond
       0A5D  _RTC_SetSecond
       0A75  _RTC_SetMinute
       0A75  RTC_SetMinute
       0A8D  RTC_SetHour
       0A8D  _RTC_SetHour
       0AA5  _PWM16_CH1_ISR
       0AA6  _PWM16_CH1_EnableInt
       0AA6  PWM16_CH1_EnableInt
       0AAA  _PWM16_CH1_DisableInt
       0AAA  PWM16_CH1_DisableInt
       0AAE  _PWM16_CH1_Start
       0AAE  PWM16_CH1_Start
       0AB2  _PWM16_CH1_Stop
       0AB2  PWM16_CH1_Stop
       0AB6  _PWM16_CH1_WritePeriod
       0AB6  PWM16_CH1_WritePeriod
       0ABC  _PWM16_CH1_WritePulseWidth
       0ABC  PWM16_CH1_WritePulseWidth
       0AC2  wPWM16_CH1_ReadPulseWidth
       0AC2  PWM16_CH1_wReadPulseWidth
       0AC2  _wPWM16_CH1_ReadPulseWidth
       0AC2  _PWM16_CH1_wReadPulseWidth
       0AC8  _wPWM16_CH1_ReadCounter
       0AC8  PWM16_CH1_wReadCounter
       0AC8  wPWM16_CH1_ReadCounter
       0AC8  _PWM16_CH1_wReadCounter
       0B02  _PWM16_CH0_ISR
       0B03  _PWM16_CH0_EnableInt
       0B03  PWM16_CH0_EnableInt
       0B07  _PWM16_CH0_DisableInt
       0B07  PWM16_CH0_DisableInt
       0B0B  _PWM16_CH0_Start
       0B0B  PWM16_CH0_Start
       0B0F  _PWM16_CH0_Stop
       0B0F  PWM16_CH0_Stop
       0B13  _PWM16_CH0_WritePeriod
       0B13  PWM16_CH0_WritePeriod
       0B19  PWM16_CH0_WritePulseWidth
       0B19  _PWM16_CH0_WritePulseWidth
       0B1F  _PWM16_CH0_wReadPulseWidth
       0B1F  PWM16_CH0_wReadPulseWidth
       0B1F  wPWM16_CH0_ReadPulseWidth
       0B1F  _wPWM16_CH0_ReadPulseWidth
       0B25  _PWM16_CH0_wReadCounter
       0B25  wPWM16_CH0_ReadCounter
       0B25  _wPWM16_CH0_ReadCounter
       0B25  PWM16_CH0_wReadCounter
       0B5F  LED_Blue_On
       0B5F  _LED_Blue_On
       0B63  _LED_Blue_Stop
       0B63  LED_Blue_Stop
       0B63  _LED_Blue_Start
       0B63  LED_Blue_Off
       0B63  LED_Blue_Start
       0B63  _LED_Blue_Off
       0B65  LED_Blue_Switch
       0B65  _LED_Blue_Switch
       0B7D  _LED_Blue_Invert
       0B7D  LED_Blue_Invert
       0B8C  LED_Blue_GetState
       0B8C  _LED_Blue_GetState
       0B9D  _Counter8_RF_clk_ISR
       0B9E  _Counter8_RF_clk_EnableInt
       0B9E  Counter8_RF_clk_EnableInt
       0BA2  Counter8_RF_clk_DisableInt
       0BA2  _Counter8_RF_clk_DisableInt
       0BA6  Counter8_RF_clk_Start
       0BA6  _Counter8_RF_clk_Start
       0BAA  _Counter8_RF_clk_Stop
       0BAA  Counter8_RF_clk_Stop
       0BAE  _Counter8_RF_clk_WritePeriod
       0BAE  Counter8_RF_clk_WritePeriod
       0BB1  _Counter8_RF_clk_WriteCompareValue
       0BB1  Counter8_RF_clk_WriteCompareValue
       0BB4  _Counter8_RF_clk_bReadCompareValue
       0BB4  _bCounter8_RF_clk_ReadCompareValue
       0BB4  Counter8_RF_clk_bReadCompareValue
       0BB4  bCounter8_RF_clk_ReadCompareValue
       0BB7  _bCounter8_RF_clk_ReadCounter
       0BB7  bCounter8_RF_clk_ReadCounter
       0BB7  Counter8_RF_clk_bReadCounter
       0BB7  _Counter8_RF_clk_bReadCounter
       0BE8  _Counter16_PwrUpd_ISR
       0C73  Counter16_PwrUpd_EnableInt
       0C73  _Counter16_PwrUpd_EnableInt
       0C77  _Counter16_PwrUpd_DisableInt
       0C77  Counter16_PwrUpd_DisableInt
       0C7B  Counter16_PwrUpd_Start
       0C7B  _Counter16_PwrUpd_Start
       0C7F  _Counter16_PwrUpd_Stop
       0C7F  Counter16_PwrUpd_Stop
       0C83  _Counter16_PwrUpd_WritePeriod
       0C83  Counter16_PwrUpd_WritePeriod
       0C89  Counter16_PwrUpd_WriteCompareValue
       0C89  _Counter16_PwrUpd_WriteCompareValue
       0C8F  _Counter16_PwrUpd_wReadCompareValue
       0C8F  _wCounter16_PwrUpd_ReadCompareValue
       0C8F  Counter16_PwrUpd_wReadCompareValue
       0C8F  wCounter16_PwrUpd_ReadCompareValue
       0C95  _Counter16_PwrUpd_wReadCounter
       0C95  Counter16_PwrUpd_wReadCounter
       0C95  wCounter16_PwrUpd_ReadCounter
       0C95  _wCounter16_PwrUpd_ReadCounter
       0CD3  __UserModules_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                            text   0CD3   0F87 =   3975. bytes (rel,con,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       0CD3  Delay10msTimes
       0CD3  _Delay10msTimes
       0CD3  __text_start
       0CE0  _Delay50uTimes
       0CE0  Delay50uTimes
       0CE6  Delay50u_Table
       0CEE  Delay50u
       0CEE  _Delay50u
       0D02  _gps_signal
       0DB3  _rf_signal
       0E7A  _main
       10BA  _set_power
       10D9  _override_enable
       10F2  _update_power
       1160  _schedule_processing
       11E0  _schedule_init
       121E  _rtc_update
       1280  _check_fld
       12CD  _NMEA_GetField
       1408  _NMEA_handle_packet
       1530  _NMEA_GetTimeUTC
       1744  _str_cmp
       1795  _str_cmp_const
       17E7  _byte_to_bcd
       181E  _bcd_to_byte
       1855  _utc_to_local
       1948  _strlenLMM
       1953  _strlen
       196E  _atoi
       1AAF  _isdigit
       1AD0  _isspace
       1AF1  _strncat
       1B9E  _strncpy
       1C5A  __text_end
       1C5A  __xidata_start
       1CB5  __xidata_end

Area                               Start  End    Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                             TOP   0000   0154 =    340. bytes (abs,ovr,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       0080  __Start
       0151  _bGetPowerSetting
       0151  bGetPowerSetting

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                    InterruptRAM   0000   0005 =      5. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       0000  _RX8_RF_fStatus
       0000  RX8_RF_fStatus
       0001  _RX8_RF_bRxCnt
       0001  RX8_RF_bRxCnt
       0002  RX8_GPS_fStatus
       0002  _RX8_GPS_fStatus
       0003  _RX8_GPS_bRxCnt
       0003  RX8_GPS_bRxCnt
       0004  NO_SHADOW
       0004  Port_1_Data_SHADE
       0004  _Port_1_Data_SHADE
       0004  _NO_SHADOW

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                     RX8_GPS_RAM   0000   0011 =     17. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       00B9  _RX8_GPS_aRxBuffer
       00B9  RX8_GPS_aRxBuffer

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                      RX8_RF_RAM   0000   0011 =     17. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       00A9  RX8_RF_aRxBuffer
       00A9  _RX8_RF_aRxBuffer

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
               virtual_registers   00C9   000F =     15. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       00C9  __rZ
       00CA  __rY
       00CB  __rX
       00CC  __r11
       00CD  __r10
       00CE  __r9
       00CF  __r8
       00D0  __r7
       00D1  __r6
       00D2  __r5
       00D3  __r4
       00D4  __r3
       00D5  __r2
       00D6  __r1
       00D7  __r0

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                            data   0000   01C2 =    450. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       0000  __data_start
       0005  _NMEA_buffer_gps
       0057  _NMEA_SHFTL
       00D8  _local_datetime
       00E0  _gps_datetime
       00E8  _nmea_shftl_empty
       00EE  _nmea_gprmc_empty
       00F4  _NMEA_cmd_received
       00F6  _NMEA_pointer_rf
       0100  _NMEA_GPRMC
       0152  _NMEA_buffer_rf
       01A4  _fld_buf
       01F6  _override_counter
       01FA  _power_target
       01FC  _override
       01FE  _NMEA_pointer_gps

Files Linked      [ module(s) ]

./obj/boot.o	[ boot.asm ]
obj/delay.o	[ delay.asm ]
obj/main.o	[ main.c ]
<library>	[ tx8_debugint.asm, tx8_debug.asm, rx8_rfint.asm, rx8_rf.asm, rx8_gpsint.asm, rx8_gps.asm, rtcint.asm ]
[ rtc.asm, pwm16_ch1int.asm, pwm16_ch1.asm, pwm16_ch0int.asm, pwm16_ch0.asm, psocconfigtbl.asm ]
[ psocconfig.asm, led_blue.asm, counter8_rf_clkint.asm, counter8_rf_clk.asm, counter16_pwrupdint.asm ]
[ counter16_pwrupd.asm, rZ.asm, rY.asm, rX.asm, r11.asm, r10.asm, r9.asm, r8.asm, r7.asm, r6.asm, r5.asm ]
[ r4.asm, r3.asm, r2.asm, r1.asm, r0.asm, divmodu_8x8_8_util.asm, i_div8_block_util.asm, strlen.s ]
[ atoi.s, isdigit.s, isspace.s, ctype.s, strncat.s, strncpy.s ]

Area Definitions

-blit:0x190.0x3fff
-bdata:0.0x2ff
-BInterruptRAM:0	allocated at: 0
-Bvirtual_registers	allocated at: 0xc9
-Bfitolamp_slave_RAM	allocated at: 0
-rwh:SSCParmBlk:0xf7.0xff

